### ISSUE TITLE
Cache generated images?

### ISSUE THREAD

**Issue by kevinrenskers** [JonasKruckenberg/imagetools#522]
I'm using vite-imagetools in a SvelteKit project, and due to the many images that the site is using, creating a build takes almost 3 minutes. When I remove the vite-imagetools plugin, creating a build takes about 20 seconds. This is a huge huge difference, and it kind of doesn't make sense to me that the images are getting generated with every single build, as the source images basically never change.

Is there a way to cache the generated images, so that when you create the next build, it can just reuse the earlier generated images instead of having to create them all over again?

**Comment by benmccann** [comment]
Would someone be able to try the caching plugin and let me know if it works this use case? https://github.com/vitejs/vite/pull/10671 (see the "Try it" heading for instructions on setting it up)

**Comment by ArnaudBarre** [comment]
Hi! Vite team member here.
One of the reason we decided to currently not continue experimenting with caching is that because it's global, cache invalidation will happen too often (lock update, config update or even some env update). Plus the caching was only for dev.
So for the now the idea is: making core fast, let plugins with slow process do caching. In the future we may provide helpers to help plugin authors deal with caching (apparently something that Parcel does well) but for now you will be on your own.

**Comment by JonasKruckenberg** [comment]
Yeah we had on-disk caching in the 1.x version of this plugin (it was actually disk first) but maintaining that folder and purging old images was a total nightmare. 
Maybe I'm missing something and it has been years since I last did something like this but the only obvious solution that comes to mind is maintaining some sort of cache manifest 🤔
Or maybe iterating through and checking the lastModified time though I don't know if that would cause weird issues with CI builds

**Comment by benmccann** [comment]
Thanks for the update @ArnaudBarre. I know we decided not to merge anything in Vite core to deal with caching at the moment, but wasn't sure what thoughts were around it longer term - e.g. whether you might be maintaining the caching plugin or revisiting that approach if we find places where Vite still has opportunities for improvement.

**Comment by JonasKruckenberg** [comment]
Yeah so regardless I kinda don't want to deal with implementing caching. I absolutely see the benefit but as I stated earlier last time around it was a nightmare. 
If someone wants to submit a PR for it I would be happy to get it across the finish line and released.
Having this be exposed by vite as part of the plugin API though would be obviously ideal

**Comment by benmccann** [comment]
See https://github.com/vitejs/vite/pull/14333

**Comment by Robin-Sch** [comment]
Any update for this? I have 71 images and the build time is approximately 15 minutes. If I exclude them it's "just" 2 minutes.

**Comment by julien-blanchon** [comment]
This is a nightmare without caching ...
