### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by tchak** [JonasKruckenberg/imagetools#70]
I am trying to use vite-imagetools with React and Typescript. Image imports with query params in them are marked as unknown imports. I understand why it is the case, my question is, do you know of any good solution to deal with this apart from manually typing all my assets?

**Comment by JonasKruckenberg** [comment]
As I'm using typescript for all of my projects, I am very aware of this issue. A type declaration of images would have to look something like this
```ts
declare module "*.jpg?*"
declare module "*.webp?*"
// etc.
```
Because we only want to provide types for imports that use directives. The problem is though that typescript at the moment only allows one star (*) in a pattern at a time, so using two stars will result in typescript complaining.
I know it's not ideal and I will raise an issue with the typescript folks at some point (its on my backlog) but for now there is no real solution for this :/

**Comment by andyliuhaowen** [comment]
Is there an issue under TS to track this? I tried to look for one but couldn't. It's probably buried somewhere among the 5k+ issues for TS.

**Comment by andyliuhaowen** [comment]
Thanks for the quick update on things! And of course thanks so much for this awesome project I've come to depend on daily. I'll follow up under TS to hopefully get this to work.

**Comment by TedMeftah** [comment]
One way I'm getting around this is I have this declaration:

```ts
declare module '*&img';
```
then I add the `&img` to the end of my imports like this:

```ts
import image from '$lib/assets/image.png?width=1000&format=webp&img';
```
